
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarServer from "./api/text/NavbarServer";
import Navbar from "./components/Navbar";
import FooterMobil from "./components/FooterMobil";
import FooterDesktop from "./components/FooterDesktop";
import Provider from './components/Provider';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar/>
       
        {children}
        <div className="hidden relative py-6 sm:flex flex-col justify-center">
        <FooterDesktop />
      </div>
      <div className="sm:hidden relative flex flex-row my-4">
        <FooterMobil />

      </div>
      </body>
    </html>
  );
}
